FROM node:14

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN chmod +x /app/wait-for-it.sh

CMD ["./wait-for-it.sh", "mysql:3306", "--", "npx", "nodemon", "api/server.js"]
