version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    user: "1000:50"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  app:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  mysql_data:
